triggers:
- envs: []
  last_enabled_at: 2024-02-03 21:14:32.407616
  name: Daily Schedule
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-03 05:00:00
  status: active
  variables: {}
